import type { Metadata } from "next";
import { Inter } from "next/font/google"; // Geistの代わりにInterをインポート
import "./globals.css";

const inter = Inter({ subsets: ["latin"] }); // Interフォントを読み込む

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* classNameにinter.classNameを適用 */}
      <body className={inter.className}>{children}</body>
    </html>
  );
}